'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let ws,state,target=null,ended=false;
function send(m){if(ws?.readyState===1)ws.send(JSON.stringify(m));else $('notice').textContent='连接已断开，正在重连';}
const voice=new Voice(send,t=>$('voiceStatus').textContent=t);
function connect(){ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}`);ws.onopen=()=>{$('notice').textContent='已连接';const token=sessionStorage.getItem('moonToken');if(token)send({type:'resume',token});};ws.onmessage=async e=>{const m=JSON.parse(e.data);if(m.type==='session')sessionStorage.setItem('moonToken',m.token);if(m.type==='left'){sessionStorage.removeItem('moonToken');state=null;voice.disconnect();$('room').innerHTML='';$('setup').hidden=false;}if(m.type==='error'){$('notice').textContent=m.message;if(m.message.includes('凭据已失效'))sessionStorage.removeItem('moonToken');}if(m.type==='state'){if(state?.game?.revision!==m.game?.revision)target=null;state=m;voice.sync(m);render();}if(m.type==='signal')await voice.signal(m);};ws.onclose=()=>{voice.disconnect();$('notice').textContent='断线，2秒后恢复连接';setTimeout(connect,2000);};}
$('create').onclick=()=>send({type:'create',name:$('name').value,count:+$('count').value,selfSave:$('selfSave').checked,hunterFirst:$('hunterFirst').checked});$('join').onclick=()=>send({type:'join',name:$('name').value,code:$('code').value});$('mic').onclick=()=>voice.enable();
const labels={wolf:'狼人讨论与击杀',seer:'预言家查验',witch:'女巫用药',hunter:'猎人开枪',lastWords:'首日遗言',speech:'轮流发言',vote:'投票',end:'游戏结束'};
function render(){if(!state)return;$('setup').hidden=true;const g=state.game,me=state.players.find(p=>p.id===state.self);let buttons='';const btn=(a,t)=>`<button data-action="${a}">${t}</button>`;
if(g){if(g.phase==='wolf'&&g.role==='狼人')buttons+=btn('kill','确认击杀目标');if(g.phase==='seer'&&g.role==='预言家')buttons+=btn('inspect','查验目标');if(g.phase==='witch'&&g.role==='女巫')buttons+=(g.medicine.save&&g.victim?btn('save','使用解药'):'')+(g.medicine.poison?btn('poison','毒杀目标'):'')+btn('skip','不用药');if(g.current===state.self&&['speech','lastWords'].includes(g.phase))buttons+=btn('finish','结束发言');if(g.phase==='hunter'&&g.current===state.self)buttons+=btn('shoot','开枪／未选目标则放弃');if(g.phase==='vote')buttons+=btn('vote','投票／未选目标则弃票');}
$('room').innerHTML=`<section class="${g&&['speech','vote','lastWords','hunter'].includes(g.phase)?'day':''}"><h2>房间 ${esc(state.code)} · ${state.players.length}/${state.count}</h2>${g?`<h3>第 ${g.day} 天 · ${['wolf','seer','witch'].includes(g.phase)?'夜晚':'白天'} · ${labels[g.phase]}</h3><p>当前发言：${esc(g.players.find(p=>p.id===g.current)?.name||'—')} <span id="timer"></span></p><p>你的身份：${esc(g.role)} · ${g.canSpeak?'允许发言':'禁止发言'}</p>${g.phase==='witch'&&g.role==='女巫'?`<p>解药：${g.medicine.save?'剩余1':'已用完'}；今晚刀口：${g.medicine.save?esc(g.players.find(p=>p.id===g.victim)?.name||'无人'):'不可见'}</p>`:''}`:`<button id="ready">${me.ready?'取消准备':'准备'}</button>${state.host===state.self?'<button id="start">满员且全部准备后开始</button>':''}`}<div class="players">${state.players.map(p=>{const x=g?.players.find(x=>x.id===p.id);return `<button data-player="${p.id}" class="${x&&!x.alive?'dead':''}" style="outline:${target===p.id?'2px solid gold':'none'}">${esc(p.name)}<br>${x?(x.alive?'存活':'死亡 · 观战'):p.ready?'已准备':'未准备'} ${p.connected?'':'离线'}${x?.role?'<br>'+esc(x.role):''}</button>`}).join('')}</div>${buttons}<button id="leave">退出房间</button><p>死亡后仅首日遗言阶段可发言，其余时间仅观战。</p></section>${g?`<section><h3>公开日志</h3><pre>${esc(g.logs.join('\n'))}</pre><h3>仅自己可见</h3><pre>${esc(g.privateLog.join('\n'))}</pre></section>`:''}`;
document.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>{target=target===b.dataset.player?null:b.dataset.player;render();});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>send({type:'action',action:b.dataset.action,target,revision:g.revision}));if($('ready'))$('ready').onclick=()=>send({type:'ready',ready:!me.ready});if($('start'))$('start').onclick=()=>send({type:'start'});$('leave').onclick=()=>send({type:'leave'});if(g?.result&&!ended){ended=true;$('winner').textContent=g.result+'阵营胜利';$('roles').textContent=g.players.map(p=>p.name+'：'+p.role).join('；');$('result').showModal();}}
setInterval(()=>{if($('timer')&&state?.game)$('timer').textContent=`剩余 ${Math.max(0,Math.ceil((state.game.deadline-Date.now())/1000))} 秒`;},250);connect();
