'use strict';
// WebRTC 点对点语音，服务端只为当前有权互听的玩家转发信令。
window.Voice=class{
 constructor(send,status){this.send=send;this.status=status;this.peers=new Map();this.rev=null;this.allowed=false;this.stream=null;}
 async enable(){try{if(!this.stream)this.stream=await navigator.mediaDevices.getUserMedia({audio:true});this.stream.getAudioTracks().forEach(t=>t.enabled=this.allowed);for(const [id,x]of this.peers){const track=this.stream.getAudioTracks()[0];const sender=x.pc.getSenders().find(s=>s.track?.kind==='audio')||x.transceiver?.sender;if(sender){await sender.replaceTrack(track);if(x.pc.signalingState==='stable'&&this.state?.self>id)await this.renegotiate(id,x);}}this.status(this.allowed?'麦克风已开启':'麦克风已授权，等待发言权限');}catch(e){this.status('麦克风不可用：'+e.message);}}
 reset(){this.peers.forEach(x=>{x.pc.close();x.audio.remove()});this.peers.clear();}
 sync(s){this.state=s;this.allowed=!!s.game?.canSpeak;this.stream?.getAudioTracks().forEach(t=>t.enabled=this.allowed);if(this.rev!==s.game?.revision){this.reset();this.rev=s.game?.revision;}for(const[id,x]of this.peers)if(!s.voicePeers.includes(id)){x.pc.close();x.audio.remove();this.peers.delete(id)}for(const id of s.voicePeers)if(id>s.self&&!this.peers.has(id))this.offer(id);}
 peer(id){if(this.peers.has(id))return this.peers.get(id);const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]}),audio=document.createElement('audio');audio.autoplay=true;audio.playsInline=true;audio.dataset.voice=id;document.body.append(audio);const x={pc,audio,pending:[],transceiver:null};this.peers.set(id,x);x.transceiver=pc.addTransceiver(this.stream?.getAudioTracks()[0]||'audio',{direction:'sendrecv',...(this.stream?{streams:[this.stream]}:{})});pc.onicecandidate=e=>{if(e.candidate)this.send({type:'signal',to:id,revision:this.rev,data:{candidate:e.candidate}})};pc.ontrack=e=>{audio.srcObject=e.streams[0]||new MediaStream([e.track]);audio.play().catch(()=>this.status('点一下页面以允许播放对方语音'))};pc.onconnectionstatechange=()=>{if(pc.connectionState==='failed')this.status('语音连接失败：当前使用 STUN，部分网络需要 TURN 中继')};return x;}
 async offer(id){try{const x=this.peer(id);await this.renegotiate(id,x)}catch(e){this.status('语音协商失败：'+e.message)}}
 async renegotiate(id,x){await x.pc.setLocalDescription(await x.pc.createOffer());this.send({type:'signal',to:id,revision:this.rev,data:{description:x.pc.localDescription}})}
 async signal(m){if(m.revision!==this.rev||!this.state?.voicePeers.includes(m.from))return;try{const x=this.peer(m.from),d=m.data;if(d.description){await x.pc.setRemoteDescription(d.description);for(const c of x.pending)await x.pc.addIceCandidate(c);x.pending=[];if(d.description.type==='offer'){await x.pc.setLocalDescription(await x.pc.createAnswer());this.send({type:'signal',to:m.from,revision:this.rev,data:{description:x.pc.localDescription}})}}else if(d.candidate){if(x.pc.remoteDescription)await x.pc.addIceCandidate(d.candidate);else x.pending.push(d.candidate)}}catch(e){this.status('语音连接出错：'+e.message)}}
 disconnect(){this.allowed=false;this.stream?.getTracks().forEach(t=>t.enabled=false);this.reset()}
};
