// 每次阶段切换销毁旧音频连接；用户同意麦克风不等于获得发言权。
window.Voice=class {
 constructor(send,status){this.send=send;this.status=status;this.peers=new Map();this.rev=null;this.allowed=false;}
 async enable(){try{this.stream=await navigator.mediaDevices.getUserMedia({audio:true});this.stream.getAudioTracks().forEach(t=>t.enabled=this.allowed);this.reset();if(this.state)this.sync(this.state);this.status('麦克风已授权，按当前发言权限开关');}catch(e){this.status('麦克风不可用：'+e.message);}}
 reset(){this.peers.forEach(x=>{x.pc.close();x.audio.remove();});this.peers.clear();}
 sync(s){this.state=s;this.allowed=!!s.game?.canSpeak;this.stream?.getAudioTracks().forEach(t=>t.enabled=this.allowed);if(this.rev!==s.game?.revision){this.reset();this.rev=s.game?.revision;}for(const [id,x]of this.peers)if(!s.voicePeers.includes(id)){x.pc.close();x.audio.remove();this.peers.delete(id);}for(const id of s.voicePeers)if(id>s.self&&!this.peers.has(id))this.offer(id);}
 peer(id){if(this.peers.has(id))return this.peers.get(id);const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]}),audio=document.createElement('audio');audio.autoplay=true;document.body.append(audio);const x={pc,audio,pending:[]};this.peers.set(id,x);pc.addTransceiver(this.stream?.getAudioTracks()[0]||'audio',{direction:'sendrecv',...(this.stream?{streams:[this.stream]}:{})});const rev=this.rev;pc.onicecandidate=e=>{if(e.candidate)this.send({type:'signal',to:id,revision:rev,data:{candidate:e.candidate}})};pc.ontrack=e=>{audio.srcObject=new MediaStream([e.track]);audio.play().catch(()=>this.status('请点击页面后重新启用语音播放'));};pc.onconnectionstatechange=()=>{if(pc.connectionState==='failed')this.status('语音连接失败，跨网络可能需要 TURN 服务');};return x;}
 async offer(id){try{const {pc}=this.peer(id);await pc.setLocalDescription(await pc.createOffer());this.send({type:'signal',to:id,revision:this.rev,data:{description:pc.localDescription}});}catch(e){this.status(e.message);}}
 async signal(m){if(m.revision!==this.rev||!this.state?.voicePeers.includes(m.from))return;try{const x=this.peer(m.from),d=m.data;if(d.description){await x.pc.setRemoteDescription(d.description);for(const c of x.pending)await x.pc.addIceCandidate(c);x.pending=[];if(d.description.type==='offer'){await x.pc.setLocalDescription(await x.pc.createAnswer());this.send({type:'signal',to:m.from,revision:this.rev,data:{description:x.pc.localDescription}});}}else if(d.candidate){if(x.pc.remoteDescription)await x.pc.addIceCandidate(d.candidate);else x.pending.push(d.candidate);}}catch(e){this.status(e.message);}}
 disconnect(){this.allowed=false;this.stream?.getTracks().forEach(t=>t.enabled=false);this.reset();}
};
